name: Classroom Workflow

on:
  push: 
    paths:
      - 'scripts/session-6/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Display file contents
        run: cat scripts/session-6/*